### ISSUE TITLE
Create examples/demos for developers

### ISSUE THREAD

**Issue by torch2424** [sseaman/skillVC#1]
Hello!

I think it'd be pretty cool to have a demo skill, or an example skill, using this framework!

Looks super interesting, and you put ALOT of work into this! Very impressive! I'd love to help! just let me know, and I can work on this in my free time.

**Comment by torch2424** [comment]
We could probably have a demo lambda endpoint, and have people play with the skill using [echoism](https://echosim.io/welcome?next=%2F)?

**Comment by sseaman** [comment]
Interesting idea.   I've got a testing framework I'm wrapping up.  Once I complete that I can work on it.  Thanks for the suggestion!

**Comment by sseaman** [comment]
Examples have been created for:

Basic hello world

Using Handlebars in your responses
